version: '3'
services:
    ingress:
        image: nginx:stable-alpine
        ports: 
            - "12021:80"
        links:
            - api
        volumes: 
            - ./etc/nginx:/etc/nginx/conf.d
            - ./data/ingress:/data/

    api:
        # image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
        build: ./backend
        expose:
            - 80
        environment:
            - RUN_ENV=DEVELOPMENT
        volumes:
            - ./backend:/app
            - ./data/backend:/data
            - ./data/backend:/app/data
        working_dir: /app

    cls:
        build: ./models/classification
        expose:
            - 80
        volumes:
            - ./models/classification/app:/home/app
            - ./data/models/classification:/home/data
        working_dir: /home

    seg:
        build: ./models/segmentation
        expose:
            - 80
        volumes:
            - ./models/segmentation/app:/home/app
            - ./data/models/segmentation:/home/data
        working_dir: /home

    minio: 
        image: quay.io/minio/minio
        ports:
            - "9000:9000"
            - "12022:9001"
        environment: 
            - MINIO_ROOT_USER=minio
            - MINIO_ROOT_PASSWORD=minioHoneycomb
        command: server /data --console-address ":9001"
        volumes:
            - ./minio/data:/data
