CREATE TABLE session (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    segmentation_path VARCHAR(255) DEFAULT NULL,
    classification_path VARCHAR(255) DEFAULT NULL,
    transformation_path VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);